import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Header from "./components/header";
import { Theme } from "@radix-ui/themes";
import ReactQueryProvider from "./util/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Theme>
            <Header />
            {children}
          </Theme>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
